# Generated by Django 4.1.2 on 2022-10-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tickets",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("printer_model", models.CharField(max_length=20)),
                ("toner_color", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=200)),
                ("requested_by", models.CharField(max_length=50)),
            ],
        ),
    ]
